spring:
  application:
    name: ai-engine-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: 8084

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

gemini:
  apiKey: ${GEMINI_API_KEY}          # 환경변수에 설정된 API 키
  model: gemini-2.0-flash            # 사용할 Gemini 모델

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
