spring:
  application:
    name: board-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin
    redis:
      host: redis
      port: 6379

jwt:
  key: ${JWT_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
server:
  port: 8082

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

resilience4j:
  retry:
    instances:
      authClient:
        max-attempts: 3
        wait-duration: 300ms

  circuitbreaker:
    instances:
      authCircuit:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

springdoc:
  api-docs:
    path: /api/board/v3/api-docs  # 기본값이지만 명시적으로 설정해두는 게 좋음
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 직접 접근 경로

##